### ISSUE TITLE
BGSbot fails to respond to discord commands

### ISSUE THREAD

**Issue by Elite-IGAU** [SayakMukhopadhyay/bgsbot#47]
BGSBot frequently "ignores" commands sent to it from admin users. 

example (from docs):

https://elitebgs.app/bgsbot/docs
Pretty much every "factionstatus" related command is ignored 
(our faction name is intergalactic astronomical union)

This command seems to work okay:
@bgsbot bgsreport get 

This works too: 
@BGSBot monitorsystems list

However, this command is ignored:
@BGSBot monitorsystems remove HIP 19808

We also receive our automated BGS report at 00:00 UTC. so clearly some commands are working properly, yet others are not.

**Comment by SayakMukhopadhyay** [comment]
This is weird. There should be nothing that would stop you from the `factionstatus` command itself. One reason could be that the Discord API rate limit is getting hit. Will it be possible for you to join the EliteBGS Discord server so that we can get to the bottom of this? You can get an invite at https://elitebgs.app/about

**Comment by Elite-IGAU** [comment]
Joined. All channels seem to be locked/private
